/*
Mapgen command
Author: Tom Green
Date Created: 11/11/2019 
*/

module.exports = {
	name: "mapgen",
	syntax: `~mapgen`,
	description: 'Regenerates the map for testing purposes.',
	usage: [
		"~mapgen - Regenerate the map.",
	],
};

module.exports.run = (client, message) => {
	// If the user isn't the developer, return a message notifying the user that they have insufficient permissions.
	if (message.author.id !== client.config.devID) {
		return message.reply("Insufficient permissions.");
	}

	/*
	Create a variable to store the map generated by the generateMap function, 
	then save it to the user's account. After everything is done, delete the 
	original command.
	*/
	var map = client.charFuncs.generateMap(client, message.author.id);
	client.charFuncs.saveMap(client, message.author.id, map);
	message.reply("Map successfully regenerated");
	message.delete();
}